### ISSUE TITLE
RFM75/RFM75P vs RFM75W/RFM75PW?

### ISSUE THREAD

**Issue by alpytron** [jnk0le/RFM7x-lib#5]
Hi,
Do you have any ideas on what that 'W' mean in the part number suffix of these recently introduced modules?
Will the library work with them as well?
Thanks.

**Comment by jnk0le** [comment]
It looks more like component or pcb manufacturer swap rather than silicon respin. Especially that their documentation remains the same for newer version.

So I think that those modules should work.

**Comment by alpytron** [comment]
Thanks.
